/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    screens: {
      'sm': '640px',
      'md': '768px',
      'lg': '1024px',
      'xl': '1280px',
    },
    extend: {
      colors: {
        primary: '#0F766E',
        'primary-hover': '#115E59',
        'primary-light': '#CCFBF1',
        'primary-soft': '#F0FDFA',
        secondary: '#2563EB',
        'secondary-light': '#DBEAFE',
        ai: '#7C3AED',
        'ai-light': '#EDE9FE',
        ink: '#0F172A',
        'ink-soft': '#1E293B',
        success: '#059669',
        'success-light': '#D1FAE5',
        warning: '#D97706',
        'warning-light': '#FEF3C7',
        error: '#DC2626',
        'error-light': '#FEE2E2',
        'error-border': '#FCA5A5',
        'error-text': '#991B1B',
        neutral: '#64748B',
        surface: '#F5F7F6',
        'surface-raised': '#FFFFFF',
        card: '#FFFFFF',
        'card-border': '#DDE5E2',
        'field-border': '#CBD5D1',
        'text-primary': '#0F172A',
        'text-secondary': '#475569',
        'text-muted': '#64748B',
        'text-placeholder': '#94A3B8',
      },
      borderRadius: {
        'sm': '8px',
        'md': '10px',
        'xl': '14px',
        '2xl': '18px',
        '3xl': '24px',
        'full': '9999px',
      },
      boxShadow: {
        'card': '0 1px 2px rgba(15, 23, 42, 0.06), 0 1px 3px rgba(15, 23, 42, 0.08)',
        'card-hover': '0 8px 20px rgba(15, 23, 42, 0.12)',
        'elevated': '0 16px 32px rgba(15, 23, 42, 0.16)',
        'camera-control': '0 12px 30px rgba(0, 0, 0, 0.35)',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['Manrope', 'Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'SF Mono', 'Consolas', 'monospace'],
      },
      spacing: {
        'screen': '20px',
        'screen-sm': '24px',
        'screen-md': '32px',
        'screen-lg': '48px',
        'card': '16px',
        'card-sm': '20px',
        'card-md': '24px',
        'section': '12px',
        'section-sm': '16px',
        'section-md': '20px',
        'element': '8px',
        'sidebar': '280px',
      },
      maxWidth: {
        'app': '1024px',
        'content': '1280px',
        'mobile': '390px',
      },
      height: {
        'touch': '48px',
        'btn': '48px',
        'btn-primary': '56px',
        'header': '60px',
        'bottom-nav': '68px',
      },
      fontSize: {
        'display': ['28px', { lineHeight: '36px', fontWeight: '700', letterSpacing: '-0.02em' }],
        'heading-lg': ['24px', { lineHeight: '32px', fontWeight: '600', letterSpacing: '-0.01em' }],
        'heading': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'heading-sm': ['18px', { lineHeight: '26px', fontWeight: '600' }],
        'body-lg': ['17px', { lineHeight: '26px', fontWeight: '400' }],
        'body': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['15px', { lineHeight: '22px', fontWeight: '400' }],
        'small': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label': ['13px', { lineHeight: '18px', fontWeight: '500', letterSpacing: '0.01em' }],
        'caption': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      keyframes: {
        'slide-up': {
          '0%': { transform: 'translateY(100%)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'fade-in': {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        'collapse': {
          '0%': { maxHeight: '500px', opacity: '1' },
          '100%': { maxHeight: '0', opacity: '0' },
        },
        'expand': {
          '0%': { maxHeight: '0', opacity: '0' },
          '100%': { maxHeight: '500px', opacity: '1' },
        },
      },
      animation: {
        'slide-up': 'slide-up 0.3s ease-out',
        'fade-in': 'fade-in 0.2s ease-out',
        'collapse': 'collapse 0.2s ease-out forwards',
        'expand': 'expand 0.2s ease-out forwards',
      },
      transitionDuration: {
        '200': '200ms',
      },
    },
  },
  plugins: [],
}
